# Configuración de SonarQube para consulta-reemplacamiento-ui

sonar.host.url=https://sonar.sunarp.gob.pe
sonar.projectKey=consulta-reemplacamiento-ui
sonar.projectName=consulta-reemplacamiento-ui
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8

# Fuentes a analizar
sonar.sources=src

# Exclusiones (análisis)
sonar.exclusions=**/node_modules/**,**/src/app/api/**,**/src/app/core/**,**/src/app/shared/**,**/src/app/util/**,**/src/app/pipe/**,**/src/app/constant.ts,**/src/single-spa/asset-url.ts,**/src/app/app.module.ts,**/src/environments/**,**/src/main.ts

# Deshabilitar pruebas completamente
sonar.tests=
sonar.test.inclusions=

# Sin cálculo de cobertura (más simple que excluir archivo por archivo)
sonar.coverage.exclusions=src/**
sonar.cpd.exclusions=**/*.html

# Reportes de cobertura
sonar.javascript.lcov.reportPaths=coverage/consulta-reemplacamiento-ui/report-lcov/lcov.info
sonar.typescript.lcov.reportPaths=coverage/consulta-reemplacamiento-ui/report-lcov/lcov.info

#tyescript config
sonar.typescript.tsconfigPath=tsconfig.json
sonar.qualitygate.wait=false

sonar.token=sqa_ed76cca100b913bf7fff2318eeccaa5e7e37502e

